Repository horuragi/myforest, pull requests merged in 2022-09, with the labels that each got.

#40 Morgan과 Winston을 이용한 Logging 처리 구현
  .gitignore
  app.js
  package-lock.json
  package.json
  winston.js
Labels: enhancement

#43 [Feat]: 이동 로그아웃 라우트
  public/js/booking.js
  routes/index.js
  routes/users.js
  views/header.html
  views/mobile_admin_login.html
Labels: ✨ Feature

#45 Refactor: 리팩토링 메인 페이지 라우터
  lib/home_admin.js
  routes/index.js
Labels: 🔨 Refactor
